### PR TITLE
A script to create a bundle anywhere without sudo. (you can run it wi…

### PR DESCRIPTION
**Pull request by d3atiq**
…th sudo rights or copy the bundle afterwards).

Hi,

I have created another shell script, based on yours, that creates the bundle in any directory you point to. Being able to create the bundle without sudo rights, and without writing directly to /Applications, is very important to me. I prefer to manually copy the bundle to /Applications after it is created and eventually tested.

Feel free to use the additions.

Cheers,
Douglas

### CODE REVIEW

**Comment by carljmosca** [comment]
Thank you...I will take a look.  There was similar feedback from others so the not-yet-tested-much install-custom.sh was added to address this.

**Comment by carljmosca** [comment]
The other "feature" that the install-custom.sh addresses is some folks were neither cloning nor downloading the entire project thinking they could use just one script.  Therefore the install-custom.sh script as the Info.plist "embedded" in it.

**Comment by carljmosca** [comment]
Confused...you looked at the install-custom.sh?

**Comment by d3atiq** [comment]
I just modified my original script to embed rather than cat the external Info.plist.template.

**Comment by carljmosca** [comment]
"rather than"?  not seeing how that's different the "install-custom.sh"

**Comment by d3atiq** [comment]
Yes, comparing to my first script. Comparing to custom-install.sh, my changes are:
a. no forceful sudo, generate the bundle where indicated by -p
b. point to either download url or downloaded file with -f

Feel free to accept or reject, it's just a convenience addition that works for me.

**Comment by carljmosca** [comment]
install-custom.sh provides --non-root-install and --netbeans-uri (curl accepts file://)

**Comment by d3atiq** [comment]
Hmm, I didn't notice that at first.

**Comment by carljmosca** [comment]
Maybe because I didn't document it very well

**Pull request closed without merging**
